import type { Config } from "tailwindcss";

const tailwind_config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#41484a",
        "primary-container": "#0a373f",
        "on-secondary-fixed": "#001f24",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#302dbe",
        "on-primary-fixed-variant": "#244c55",
        "tertiary-container": "#1302ab",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c1c1ff",
        "inverse-surface": "#2f3131",
        "error-container": "#ffdad6",
        "surface-dim": "#dadada",
        "surface": "#f9f9f9",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#e1dfff",
        "secondary-fixed": "#afedfa",
        "background": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e2e2e3",
        "surface-tint": "#3d646d",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#8b8eff",
        "on-secondary-fixed-variant": "#004e59",
        "on-primary-fixed": "#001f25",
        "tertiary": "#08006f",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#93d0dd",
        "primary": "#002127",
        "surface-variant": "#e2e2e3",
        "outline-variant": "#c0c8ca",
        "outline": "#71787a",
        "on-surface": "#1a1c1c",
        "surface-container-high": "#e8e8e8",
        "secondary": "#256772",
        "secondary-container": "#aceaf7",
        "on-primary-container": "#79a0aa",
        "on-tertiary-fixed": "#08006c",
        "on-secondary-container": "#2b6b76",
        "inverse-primary": "#a5cdd7",
        "primary-fixed": "#c0e9f4",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-low": "#f3f3f4",
        "primary-fixed-dim": "#a5cdd7",
        "surface-container": "#eeeeee",
      },
      borderRadius: {
        DEFAULT: "8px",
        lg: "8px",
        xl: "8px",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        lg: "48px",
        xl: "64px",
        sm: "12px",
        gutter: "24px",
        "container-max": "1440px",
        base: "8px",
        xs: "4px",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "title-sm": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "title-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default tailwind_config;
